cmsis-tools-environment:
  version: 1.0.0
  generated-by: arm.cmsis-csolution version 1.70.0-test
  solution: ../project.csolution.yml
  environment:
    path:
      - /fixture-workspace/tools/cmake/bin
      - /fixture-workspace/.vcpkg/artifacts/registry/tools.open.cmsis.pack.cmsis.toolbox/2.15.0/bin
      - /fixture-workspace/.vcpkg/artifacts/registry/compilers.arm.arm.none.eabi.gcc/14.3.1/bin
    variables:
      CMSIS_PACK_ROOT: /fixture-workspace/packs
      CMSIS_COMPILER_ROOT: /fixture-workspace/compilers
      GCC_TOOLCHAIN_14_3_1: /fixture-workspace/.vcpkg/artifacts/registry/compilers.arm.arm.none.eabi.gcc/14.3.1/bin
  tools:
    - name: tools.kitware.cmake
      origin: installed
      provider:
        type: vcpkg
        id: arm.environment-manager
      directory: /fixture-workspace/tools/cmake/bin
    - name: tools.open.cmsis.pack.cmsis.toolbox
      version: 2.15.0
      origin: installed
      provider:
        type: vcpkg
        id: arm.environment-manager
      directory: /fixture-workspace/.vcpkg/artifacts/registry/tools.open.cmsis.pack.cmsis.toolbox/2.15.0
    - name: compilers.arm.arm.none.eabi.gcc
      version: 14.3.1
      origin: installed
      provider:
        type: vcpkg
        id: arm.environment-manager
      directory: /fixture-workspace/.vcpkg/artifacts/registry/compilers.arm.arm.none.eabi.gcc/14.3.1
