name: Security Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/markdown.yml'
      - '.github/markdownlint.json'
      - '.github/markdownlint.jsonc'
      - '.github/workflows/nightly.yml'
      - '.github/ISSUE_TEMPLATE/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read
      security-events: write
      packages: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout repository
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Initialize CodeQL
        id: initialize
        uses: github/codeql-action/init@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          queries: security-extended 
          languages: TypeScript
          source-root: src
          
      - name: Autobuild
        id: autobuild
        uses: github/codeql-action/autobuild@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9

      - name: Perform CodeQL Analysis
        id: analyze
        uses: github/codeql-action/analyze@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9

  osv-scan:
    permissions:
      actions: read
      checks: write
      contents: read
      security-events: write
      packages: read
    if: ${{ github.event_name == 'pull_request' }}
    name: Scan PR with OSV Scanner
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@6e4298ebc4db23e847df9b2e2de2939d6f066c67 # v2.5.1
    with:
      scan-args: |-
        --recursive
        --skip-git
        ./
