name: TPIP

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/tpip.yml
      - docs/third-party-licenses.json
      - docs/tpip-header.md
      - packages/cmsis-common/package.json
      - packages/cmsis-common/third-party-licenses.json
      - packages/cmsis-common/tpip-header.md
      - scripts/tpip-reporter.ts
      - package-lock.json
      - docs/*
      - scripts/update-tpip.ts

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  update-tpip:
    name: Update TPIP Report
    permissions:
      contents: write
      packages: read
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version-file: package.json
          registry-url: https://npm.pkg.github.com
          check-latest: false
          package-manager-cache: false

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npm ci

      - name: Update TPIP excerpt
        run: npm run tpip:update

      - name: Update TPIP report
        id: report
        run: |
          npm run tpip
          if git diff --exit-code docs/third-party-licenses.md packages/cmsis-common/third-party-licenses.md > /dev/null; then
            echo "update=0" >> $GITHUB_OUTPUT
          else
            echo "update=1" >> $GITHUB_OUTPUT
          fi

      - name: Commit Changes
        if: ${{ steps.report.outputs.update == 1 }}
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321
        with:
          message: "Update TPIP report [skip ci]"
          add: |
            docs/third-party-licenses.*
            packages/cmsis-common/third-party-licenses.*
